version: '3'
services:
  karakul-app-next:
    container_name: karakul-app-next
    build:
      context: .
      dockerfile: ./Dockerfile
    image: karakul-app-image
    restart: unless-stopped
    ports:
      - '5000:3000'
    env_file: .env.development
